[package]
name = "tiling_1d_loop"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[lints]
workspace = true

[dependencies]
settings = { path = "../../shared/settings"}
spirv-std.workspace = true
