/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Rust GPU",
  "tagline": "The future of GPU programming",
  "url": "https://rust-gpu.github.io",
  "baseUrl": "/",
  "organizationName": "rust-gpu",
  "projectName": "https://rust-gpu.github.io/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    null,
    null,
    "@gracefullight/docusaurus-plugin-tailwind"
  ],
  "presets": [
    [
      "classic",
      {
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/Rust-GPU/rust-gpu.github.io/tree/main/",
          "onInlineTags": "throw",
          "onInlineAuthors": "throw",
          "onUntruncatedBlogPosts": "throw"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "Rust GPU",
      "items": [
        {
          "href": "https://rust-gpu.github.io/rust-gpu/book/",
          "label": "Docs",
          "position": "right"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "right"
        },
        {
          "to": "/ecosystem",
          "label": "Ecosystem",
          "position": "right"
        },
        {
          "to": "/changelog",
          "label": "Changelog",
          "position": "right"
        },
        {
          "href": "https://github.com/rust-gpu/rust-gpu",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#d4d4d4",
          "backgroundColor": "#000000"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#6a737d"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#d1d5da"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "property",
              "tag",
              "boolean",
              "number",
              "constant",
              "symbol",
              "deleted"
            ],
            "style": {
              "color": "#e06c75"
            }
          },
          {
            "types": [
              "selector",
              "attr-name",
              "string",
              "char",
              "builtin",
              "inserted"
            ],
            "style": {
              "color": "#98c379"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url"
            ],
            "style": {
              "color": "#d1d5da"
            }
          },
          {
            "types": [
              "atrule",
              "attr-value",
              "keyword"
            ],
            "style": {
              "color": "#c678dd"
            }
          },
          {
            "types": [
              "function",
              "class-name"
            ],
            "style": {
              "color": "#61afef"
            }
          },
          {
            "types": [
              "regex",
              "important",
              "variable"
            ],
            "style": {
              "color": "#e5c07b"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "entity"
            ],
            "style": {
              "cursor": "help"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#d4d4d4",
          "backgroundColor": "#000000"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#6a737d"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#d1d5da"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "property",
              "tag",
              "boolean",
              "number",
              "constant",
              "symbol",
              "deleted"
            ],
            "style": {
              "color": "#e06c75"
            }
          },
          {
            "types": [
              "selector",
              "attr-name",
              "string",
              "char",
              "builtin",
              "inserted"
            ],
            "style": {
              "color": "#98c379"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url"
            ],
            "style": {
              "color": "#d1d5da"
            }
          },
          {
            "types": [
              "atrule",
              "attr-value",
              "keyword"
            ],
            "style": {
              "color": "#c678dd"
            }
          },
          {
            "types": [
              "function",
              "class-name"
            ],
            "style": {
              "color": "#61afef"
            }
          },
          {
            "types": [
              "regex",
              "important",
              "variable"
            ],
            "style": {
              "color": "#e5c07b"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "entity"
            ],
            "style": {
              "cursor": "help"
            }
          }
        ]
      },
      "defaultLanguage": "rust",
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "disableSwitch": true,
      "defaultMode": "light",
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
